""" Top-level script for the crossword editor web UI.
Contains only routing directives to handler functions
"""
from flask_session import Session

from crossword import config
# Start logging
from crossword.ui import app
from .uigrid import *
from .uimain import *
from .uipublish import *
from .uipuzzle import *
from .uiword import *
from .uiwordlists import *

log_level = config['log_level']
log_level_number = logging.getLevelName(log_level)
if type(log_level_number) == int:
    logging.basicConfig(level=log_level_number)
else:
    logging.basicConfig(level=logging.INFO)
    logging.warning("log_level must be CRITICAL, ERROR, WARNING, INFO, DEBUG, or NOTSET")
logging.info("Starting crossword server")

# Create app
app.config["JSON_SORT_KEYS"] = False
app.config["DEBUG"] = True

# Get flask secret key from an environment variable
# If the variable does not exist, use this one
# generated by os.urandom(24)
secret_key = os.getenv("FLASK_SECRET_KEY")
if not secret_key:
    secret_key = "8a77732b3699d987f0d6e8ad9bfdedb9"
app.secret_key = bytes.fromhex(secret_key)

# The following is required to add server-side session support
app.config["SESSION_TYPE"] = "filesystem"
Session(app)

#   ============================================================
#   URL routing to handler functions
#   ============================================================

# Main
app.add_url_rule('/', view_func=main_screen)

# Grid
app.add_url_rule('/grid', view_func=grid_screen)
app.add_url_rule('/grids', view_func=grids)
app.add_url_rule('/grid-changed', view_func=grid_changed)
app.add_url_rule('/grid-click', view_func=grid_click)
app.add_url_rule('/grid-delete', view_func=grid_delete)
app.add_url_rule('/grid-new', view_func=grid_new, methods=['POST'])
app.add_url_rule('/grid-open', view_func=grid_open)
app.add_url_rule('/grid-preview', view_func=grid_preview)
app.add_url_rule('/grid-rotate', view_func=grid_rotate)
app.add_url_rule('/grid-save', view_func=grid_save)
app.add_url_rule('/grid_save_as', view_func=grid_save_as)
app.add_url_rule('/grid-statistics', view_func=grid_statistics)

# Puzzle
app.add_url_rule('/puzzle', view_func=puzzle_screen)
app.add_url_rule('/puzzles', view_func=puzzles)
app.add_url_rule('/puzzle-changed', view_func=puzzle_changed)
app.add_url_rule('/puzzle-click-across', view_func=puzzle_click_across)
app.add_url_rule('/puzzle-click-down', view_func=puzzle_click_down)
app.add_url_rule('/puzzle-delete', view_func=puzzle_delete)
app.add_url_rule('/puzzle-new', view_func=puzzle_new)
app.add_url_rule('/puzzle-open', view_func=puzzle_open)
app.add_url_rule('/puzzle-preview', view_func=puzzle_preview)
app.add_url_rule('/puzzle-save', view_func=puzzle_save)
app.add_url_rule('/puzzle-save-as', view_func=puzzle_save_as)
app.add_url_rule('/puzzle-undo', view_func=puzzle_undo)
app.add_url_rule('/puzzle-redo', view_func=puzzle_redo)
app.add_url_rule('/puzzle_statistics', view_func=puzzle_statistics)
app.add_url_rule('/puzzle-title', view_func=puzzle_title, methods=['POST'])

# Publish
app.add_url_rule('/puzzle-publish-acrosslite', view_func=puzzle_publish_acrosslite)
app.add_url_rule('/puzzle-publish-nytimes', view_func=puzzle_publish_nytimes)

# Word
app.add_url_rule('/word-edit', view_func=word_edit, methods=['POST'])
app.add_url_rule('/word-reset', view_func=word_reset)

# Wordlist
app.add_url_rule('/wordlists', view_func=wordlists)


#   ============================================================
#   Mainline
#   ============================================================
if __name__ == '__main__':
    app.run()
