#!/usr/bin/env python3
"""
Generate docs/dev/endpoints.md from the live route table.

Builds the FastAPI app's routers without wiring any adapters, so no database
is needed, then uses inspect to find the source file and line of each route
function. FastAPI already knows the readable path and the required query
parameters, so nothing here has to be kept in step by hand.

Usage:
    python3 tools/dev/gen_endpoints_doc.py
"""

import inspect
import os
import sys

from fastapi import FastAPI

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT_PATH = os.path.join(ROOT, "docs", "dev", "endpoints.md")

if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

SECTION_ORDER = ["Static", "Puzzles", "Words", "Export", "Import"]


def main():
    from crossword.http_server.main import iter_routes, register_routes

    app = FastAPI()
    register_routes(app)

    sections = {name: [] for name in SECTION_ORDER}
    for route in iter_routes(app):
        for method in sorted(route.methods):
            sections[_section(route.path)].append((method, _display_path(route), route.endpoint))

    lines = [
        "# API Endpoints",
        "",
        "All routes are registered in `crossword/http_server/main.py` → `register_routes()`.",
        "",
        "> Generated by `tools/dev/gen_endpoints_doc.py` — do not edit by hand.",
        "",
        "> The running server also publishes this API as OpenAPI at `/openapi.json`,",
        "> with a browsable version at `/docs`.",
        "",
    ]
    for section in SECTION_ORDER:
        routes = sections[section]
        if not routes:
            continue
        modules = list(dict.fromkeys(_module_name(endpoint) for _, _, endpoint in routes))
        lines.append(f"## {section}")
        lines.append("")
        lines.append("Modules: " + ", ".join(f"`{module}`" for module in modules))
        lines.append("")
        lines.append("| Method | Path | Handler |")
        lines.append("|--------|------|---------|")
        for method, path, endpoint in routes:
            lines.append(f"| {method} | `{path}` | {_handler_link(endpoint)} |")
        lines.append("")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines))
    print(f"Written: {OUT_PATH}")


def _section(path):
    """Group a path under the heading it belongs to."""
    if path.startswith("/api/export"):
        return "Export"
    if path.startswith("/api/import"):
        return "Import"
    if path.startswith("/api/words") or "/words/" in path:
        return "Words"
    if path.startswith("/api/puzzles") or path == "/api/dashboard":
        return "Puzzles"
    return "Static"


def _display_path(route):
    """The route's path, with any required query parameters spelled out."""
    required = [field.name for field in route.dependant.query_params if field.field_info.is_required()]
    if not required:
        return route.path
    return route.path + "?" + "&".join(f"{name}=" for name in required)


def _module_name(endpoint):
    return os.path.basename(inspect.getfile(endpoint))


def _handler_link(endpoint):
    source_file = inspect.getfile(endpoint)
    _, start_line = inspect.getsourcelines(endpoint)
    # Path relative to docs/dev/ so the link works from that directory
    link_path = os.path.relpath(source_file, os.path.join(ROOT, "docs", "dev"))
    return f"[{endpoint.__name__}]({link_path}#L{start_line})"


if __name__ == "__main__":
    main()
