#!/usr/bin/env python3
"""
Generate the API endpoint reference from the live route table.

Builds the FastAPI app's routers without wiring any adapters, so no database
is needed, then uses inspect to find the source file and line of each route
function. FastAPI already knows the readable path and the required query
parameters, so nothing here has to be kept in step by hand.

Two files are written from the same route table:

    docs/dev/endpoints.md       For reading in the repository. Handler links
                                are relative to docs/dev/.
    docs/dev/endpoints-wiki.md  For the wiki's API-Reference page. Handler
                                links are absolute GitHub URLs, because the
                                wiki cannot resolve repository paths, and the
                                wiki-only notes are already in place. Copy it
                                over that page whole; nothing needs editing.

Usage:
    python3 tools/dev/gen_endpoints_doc.py
"""

import inspect
import os
import sys

from fastapi import FastAPI

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT_PATH = os.path.join(ROOT, "docs", "dev", "endpoints.md")
WIKI_OUT_PATH = os.path.join(ROOT, "docs", "dev", "endpoints-wiki.md")

BLOB_URL = "https://github.com/philhanna/crossword/blob/main"

if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

SECTION_ORDER = ["Static", "Puzzles", "Words", "Export", "Import"]

REPO_NOTICE = [
    "> Generated by `tools/dev/gen_endpoints_doc.py` — do not edit by hand.",
]

WIKI_NOTICE = [
    "> Generated by `tools/dev/gen_endpoints_doc.py` from the live route",
    "> registrations, as `docs/dev/endpoints-wiki.md`. Do not edit this page by",
    "> hand — regenerate it and copy that file over this page (see",
    "> [[Developer-Guide]]).",
]

# The /static mount is not an APIRoute, so it never reaches the route table.
# Only the wiki page explains its absence; in the repo the mount is visible in
# register_routes() a few lines from the doc itself.
STATIC_NOTE = [
    "Everything else under `/static/` is served by a `StaticFiles` mount rather",
    "than a route, so it does not appear in the table above.",
]


def main():
    from crossword.http_server.main import iter_routes, register_routes

    app = FastAPI()
    register_routes(app)

    sections = {name: [] for name in SECTION_ORDER}
    for route in iter_routes(app):
        for method in sorted(route.methods):
            sections[_section(route.path)].append((method, _display_path(route), route.endpoint))

    _write(OUT_PATH, _render(sections, _repo_handler_link, REPO_NOTICE))
    _write(WIKI_OUT_PATH, _render(sections, _wiki_handler_link, WIKI_NOTICE,
                                  static_note=STATIC_NOTE))


def _section(path):
    """Group a path under the heading it belongs to."""
    if path.startswith("/api/export"):
        return "Export"
    if path.startswith("/api/import"):
        return "Import"
    if path.startswith("/api/words") or "/words/" in path:
        return "Words"
    if path.startswith("/api/puzzles") or path == "/api/dashboard":
        return "Puzzles"
    return "Static"


def _display_path(route):
    """The route's path, with any required query parameters spelled out."""
    required = [field.name for field in route.dependant.query_params if field.field_info.is_required()]
    if not required:
        return route.path
    return route.path + "?" + "&".join(f"{name}=" for name in required)


def _render(sections, handler_link, notice, static_note=None):
    """
    Build one flavor of the reference.

    Args:
        sections: Routes grouped by heading, as built in main()
        handler_link: Callable turning a route function into a markdown link
        notice: The do-not-edit admonition, as a list of lines
        static_note: Optional lines to add after the Static table

    Returns:
        The whole document as a string
    """
    lines = [
        "# API Endpoints",
        "",
        "All routes are registered in `crossword/http_server/main.py` → `register_routes()`.",
        "",
        *notice,
        "",
        "> The running server also publishes this API as OpenAPI at `/openapi.json`,",
        "> with a browsable version at `/docs`.",
        "",
    ]
    for section in SECTION_ORDER:
        routes = sections[section]
        if not routes:
            continue
        modules = list(dict.fromkeys(_module_name(endpoint) for _, _, endpoint in routes))
        lines.append(f"## {section}")
        lines.append("")
        lines.append("Modules: " + ", ".join(f"`{module}`" for module in modules))
        lines.append("")
        lines.append("| Method | Path | Handler |")
        lines.append("|--------|------|---------|")
        for method, path, endpoint in routes:
            lines.append(f"| {method} | `{path}` | {handler_link(endpoint)} |")
        lines.append("")
        if static_note and section == "Static":
            lines.extend(static_note)
            lines.append("")
    return "\n".join(lines)


def _module_name(endpoint):
    return os.path.basename(inspect.getfile(endpoint))


def _repo_handler_link(endpoint):
    """Link a handler by a path relative to docs/dev/, where the doc lives."""
    source_file, start_line = _handler_location(endpoint)
    link_path = os.path.relpath(source_file, os.path.join(ROOT, "docs", "dev"))
    return f"[{endpoint.__name__}]({link_path}#L{start_line})"


def _wiki_handler_link(endpoint):
    """Link a handler by absolute URL; the wiki cannot resolve repository paths."""
    source_file, start_line = _handler_location(endpoint)
    link_path = os.path.relpath(source_file, ROOT).replace(os.sep, "/")
    return f"[{endpoint.__name__}]({BLOB_URL}/{link_path}#L{start_line})"


def _handler_location(endpoint):
    """The source file and first line of a route handler."""
    source_file = inspect.getfile(endpoint)
    _, start_line = inspect.getsourcelines(endpoint)
    return source_file, start_line


def _write(path, text):
    with open(path, "w") as f:
        f.write(text)
    print(f"Written: {path}")


if __name__ == "__main__":
    main()
